# http port set
server:
  port: 8518  
  
# Oracle Connect
spring:
  datasource:
    url: jdbc:oracle:thin:@localhost:1521/xe
    username: scott
    password: tiger
    driver-class-name: oracle.jdbc.driver.OracleDriver
    
  # ORM JPA
  jpa:  
    hibernate:
      ddl-auto : none
  
  # gmail Transfer   
  mail:
    host: smtp.gmail.com
    port: 587
    username: ttaekwang3@gmail.com
    password: 
    properties:
      mail:
        smtp:
          auth: true
          starttls.enable: true  
  
  
  
      
  #view resolver(Templete ->JSP Use)    
  mvc:
    view:
      prefix:  /WEB-INF/views/
      suffix: .jsp
      
      
# Mybatis
mybatis:
  # dto Location
  # type-aliases-package: com.oracle.sBootMybatis03.model   
  # XML Location
  config-location: classpath:configuration.xml
  mapper-locations: classpath:mappers/*.xml
